version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  service-b:
    build:
      context: ./service-b
    container_name: service-b
    volumes:
      - ./service-b/app:/app
    networks:
      - backend
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=flask_db

  service-c:
    build:
      context: ./service-c
    container_name: service-c
    volumes:
      - ./service-c/app:/app
    networks:
      - backend
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=flask_db

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    networks:
      - backend

networks:
  backend: